[package]
name = "stadtradeln"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = "0.11.18"
actix-web = "4.3.1"
openssl = "0.10.52"