name: Build image

on:
  push:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - uses: Swatinem/rust-cache@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - name: Build
        uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: build
          args: --release --target x86_64-unknown-linux-musl --all-features --verbose
      - name: Semantic Pre-Release Action
        id: semantic
        uses: codfish/semantic-release-action@v2
        with:
          branches: main
          dry_run: true
          additional_packages: |
            ['@semantic-release/git']
          plugins: |
            ['@semantic-release/commit-analyzer', '@semantic-release/release-notes-generator', '@semantic-release/github', '@semantic-release/git']
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Build & Push Docker image
        run: docker build -t ${{ secrets.DOCKER_USER }}/stadtradeln:${{ steps.semantic.outputs.release-version  }} -f ./Dockerfile --push .
      - name: Semantic Release Action
        uses: codfish/semantic-release-action@v2
        with:
          branches: main
          dry_run: false
          additional_packages: |
            ['@semantic-release/git']
          plugins: |
            ['@semantic-release/commit-analyzer', '@semantic-release/release-notes-generator', '@semantic-release/github', '@semantic-release/git']
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}