name: Build image

on:
  push:
    branches:
      - 'main'

jobs:
  build-image:
    name: build Image
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_TOKEN }}
    - name: Semantic Pre-Release Action
      id: semantic
      uses: codfish/semantic-release-action@v2
      with:
        branches: main
        dry_run: true
        additional_packages: |
          ['@semantic-release/git']
        plugins: |
          ['@semantic-release/commit-analyzer', '@semantic-release/release-notes-generator', '@semantic-release/github', '@semantic-release/git']
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Build & Push Docker image
      run: docker buildx build -t ${{ secrets.DOCKER_USER }}/stadtradeln:${{ steps.semantic.outputs.release-version  }} -f ./Dockerfile --push --platform=linux/arm64,linux/amd64 .
    - name: Semantic Release Action
      uses: codfish/semantic-release-action@v2
      with:
        branches: main
        dry_run: false
        additional_packages: |
          ['@semantic-release/git']
        plugins: |
          ['@semantic-release/commit-analyzer', '@semantic-release/release-notes-generator', '@semantic-release/github', '@semantic-release/git']
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}